Server:
  port: 8899

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yangyang_erp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&verifyServerCertificate=false&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/static/admin-ui/

mybatis-plus:
  global-config:
    enable-sql-runner: true
